pipeline {
    agent any
    
    environment {
        GIT_REPO_LINK = 'https://github.com/rajibul2009/full-stack-mern-app.git'
        REPO_BRANCH = 'master'
    }

    stages {
        stage("Repo Clone") {
            steps {
                echo "Project Cloning..."
                git url: "${GIT_REPO_LINK}", branch: "${REPO_BRANCH}"
                sh "ls -lah"
                echo "Check inside run_mern_stack_with_docker_compose directory"

                dir("run_mern_stack_with_docker_compose") {
                    sh "ls -lah"
                    dir("backend"){
                        sh "ls -lah"
                    }
                }

            }
        }

        stage("Prepare docker-compose file") {
            steps {
                echo "Preparing docker-compose.yaml..."
                dir("run_mern_stack_with_docker_compose") {
                    sh """
                    ls -lah
                    rm -f docker-compose.yaml
                    ls -lah
                    """
                    writeFile file: 'docker-compose.yaml', text: """
version: '3.9'

services:
  # MySQL Database Service
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: crud_operations
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - todo_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Node.js Backend Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-api
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=mysql
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
      - DB_DATABASE=crud_operations
    volumes:
      - ./server:/usr/src/app
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - todo_network

volumes:
  db_data:

networks:
  todo_network:
    name: todo_network
    external: true
"""
                }
            }
        }

        stage("Docker image build") {
            steps {
                echo "Building Docker images..."
                dir("run_mern_stack_with_docker_compose") {
                    sh "docker compose build"
                }
            }
        }

        stage("Docker Compose down"){
            steps {
                echo "Stopping existing Docker services..."
                dir("run_mern_stack_with_docker_compose") {
                    sh "docker compose down"
                }
            }
        }

        stage("Docker Compose up - detached mode"){
            steps {
                echo "Starting Docker services in detached mode..."
                dir("run_mern_stack_with_docker_compose") {
                    sh "docker compose up -d"
                }
            }
        }
    }

    post {
        always {
            echo 'Cleaning workspace...'
            cleanWs()
        }
        failure {
            echo 'Build failed.'
        }
        success {
            echo 'Build successful!'
        }
    }
}
